apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:Qd+MWcMDG6OQjAXIOFtP4eUDk70NnLRclX2f/TJXHZH203fm+vhixw==,iv:WA7wCDoKYzRwAr0T2CA5DmtFofMmC8komJEGsgf4aas=,tag:jwRd4/MLpO6EqFXKHfvD9Q==,type:str]
sops:
  age:
    - recipient: age1jth9rdg3ar3c94qjx38tw8p32xlj8pst3s709e4fedjx5dws3yqs2y8e90
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4c3V3d3FLODZuNkNKL3Z3
        RTV6RUJDQlNWcFVydGNRc1hlZFJjMDRIWTBvCjd2SEN4UWtxa0VvcEpNZjdlOEEv
        VHhSN21WektDeUpSZG9KWUVtanNGRU0KLS0tIExramVCdTdLK0xZRmgxaWxWdlZv
        Vzl4V1hhdzZPRHNyU0k2ZGRJalhxUDAKZDlbEizwAAbxL0tSbfQlkkFiYeRtD1tD
        AOuzT6IQDl6WgOInLyoNobSt2QkraIy6TlCobLmaCivK07fcMdojkA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-14T16:56:25Z"
  mac: ENC[AES256_GCM,data:XPJKH6JG0a+/+vHcZVb+ZmwxjhDKbYOTH9Tiqro2Bv2ST93Jp0z+oVGx1NnNnxMgsYEvgjq50xw5SCCEYJtYz6i7S/qvb0c4PIHc1CIs20yebQmOvAsWFSN4Kiip5W+xrQmcy0Jch8twtLGxnSJwrrPlC3O7T2/gG0OxhmJ/Ngk=,iv:KFkhDR5gp5ugzRfziN5bE8RIFQkiTHAfBaZiIiEg/ME=,tag:1+XRDRJKPEBRWmPn7uNBEw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
