apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:b8ytNJgdwYbgYth1E7WU71KbAn+51mXEiKgARY8HSibetTCo8oOTDA==,iv:CauVmjfOeW7MejknhwrjDQdr2DGBkGcJD0uUOYqTE4w=,tag:msgi/gM+d0E87V2ZvMlZRg==,type:str]
sops:
  age:
    - recipient: age1jth9rdg3ar3c94qjx38tw8p32xlj8pst3s709e4fedjx5dws3yqs2y8e90
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWWtaWGwyTkIxZ2xrclhU
        MkdqcnNFY0piWWo5U0dPc1d6RDN6NWZFcjFRCmx2S1JqcEpGWHFoSms0OFZ2ZFoz
        SjFPYmtXcGwyK25VOHpWSHdSek9ia0kKLS0tIG9TelZVMy9TYVRrVUR2NzE2SGtQ
        N0FGUTdVNkJEZFdNbEtLcmtETU4yOXcKhMpQd/9BC/HCdWdgLverV3Vuu89YUhXe
        C2fhyiFlLwiDppqTVuSQTkjRt+En8c2qJo5J9H2UMJ8sA6RmT2mt+Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-14T05:35:19Z"
  mac: ENC[AES256_GCM,data:tdyk9SeKZ/zY71EubWjHqQQC4GPrxHUs7gtOFZHLZ+77ubjMeqqg/tGBXXGhutLM12UImVhyb6Gezpq1zRAjG1Ctj6ARWX1rdsR5xOqWharfZn8sq0tExCBmQDPnZe04Vc2v+Dh+n4OBHt/lXR5Q4fWzEYqEM8047XibPub4gTc=,iv:EGzf80r+cxvt5JwlRee1mbVueZFbOlpPg7GzTApflNY=,tag:buUlQ+RsWqapHwAeNlV26w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
