apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:O1wDWfI3X5sR4AjXpGtWmWG5FX1yA+tQ7OnBmH18MuBV/BWmNGemJg==,iv:On5oE3sCkcty3bzaa9r3Z5AYns0HwGWy1YrHZixUZo0=,tag:eS3sniumLw0pEFWaoZA05A==,type:str]
sops:
  age:
    - recipient: age1jth9rdg3ar3c94qjx38tw8p32xlj8pst3s709e4fedjx5dws3yqs2y8e90
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNy90Ukh5MW5ubVpQa0NT
        NkJQQmNON0RMKytqaStvSUVtWDNhRFVjWkFZCmhRVHZ4b3NSSGFsR0RyUlM5djVK
        UHZ5THdtR0xEQm9wSFFJUzZWcEdNRDAKLS0tIGxORUJJLzBQZDI2WENEempNOWtN
        SU9tT2M1ZWtROXkxRHVxOEptc2RJdHMKXBQRqOgSrUg3F0CmpjxQ+Zd2LIrh/TgP
        1BYk0QPXY8BCVXGNi1kxl5e3TwXabx00EF1hESgHaE56dvISl9WywQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-14T13:54:14Z"
  mac: ENC[AES256_GCM,data:6vxoVq0pRQjh2EAszQ0vlMDsIArWXprytOsiV+YrGovdObgh0LgQvf0/JmiwzUAY8Z9UyfqgAoStQAS1OLHS1lFJkSscoUL/+zLgcKlA3lfZI95i/AqE/bvpqU19slt456aM7H49w/712qdLwZFYtdYHx418Cc7h0IuCUMGq/ho=,iv:DGYx0TSl3tQGKyb6NTda1rbs/20scRHqyaPis0k0P8Y=,tag:fZsH4aG/OGfvGt6OCgzQxw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
