apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:/h6b+j7N9qLj3bdjwoej0Ql2rCDPUWjnxiWgk09TTrbLUQiH8HwNBw==,iv:t1F/2DESOkaGrA5RNWoDGA+BH+Ba4d7k//CrpuKxwPY=,tag:89v6GYqoIiO+fV9cKNwzJw==,type:str]
sops:
  age:
    - recipient: age1jth9rdg3ar3c94qjx38tw8p32xlj8pst3s709e4fedjx5dws3yqs2y8e90
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQzZhTFUyVVNRcDRWVUZs
        WmF3VVg4b3dWN3ZBRVB2SDBsNytvbW95V0hrClo2RWlyaDNNa2NQdXhQQWlMcEhp
        czRhNWFoQm9kY1ArOXRQQU1Falp3c1EKLS0tIDRzRUlBMXFXQ2lHWHMwQ3YyQWZh
        S0NGVWVGTDVXSXlCbzJOc1ZlMmdjNE0Kc1nZtz7/NMpptAcJWZ7dgoR5FYBDKroX
        Yh6sSmNc9+Kti8GHg0OULY444DyzSWtcjqrOnpGHCPrYfMvbzq9/gA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-14T05:03:45Z"
  mac: ENC[AES256_GCM,data:3/G690/bD+CvuDqla6m0X+ozn3nRJxZWAborYIItFiCpMw9Qxi3UIsDwwnSsf8bdxKhhKrYB4BBDcLOYU9TxsUFC/1j82BcH5APiOJWgkNC5xDpLeAcVoQBwro1N4tBbo6VIITTRLH+oiiZSOsHkcO+qf+4GZ13wasFYSz6FD3g=,iv:5z2QlizAPWLHj9iiHlsTh9iN9N5RnkHdjbrmZNQ9csY=,tag:/UQZx9QGCLg6/Hmz2E1QbA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
