apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ZJjGtrb5mGEd/RjptMLcxa/r,iv:xIt8RJa4oKw/ALA8aAqjPMwTH1dxqwZDbnfw7twYK+4=,tag:4bFcvL3kvDawqzsvYjUVag==,type:str]
sops:
  age:
    - recipient: age1jth9rdg3ar3c94qjx38tw8p32xlj8pst3s709e4fedjx5dws3yqs2y8e90
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0c1NTR1VRdGVJcDFOTHV4
        d2J2NE55bWY3Q0Q0R3V5UkhxTkRFcDNYdmpJCmVReCtNb3R0ZjNTYXo1RTVMS2tQ
        YzI3dDdkUEFZeXl2ejFvendkK0t0OU0KLS0tIHVlVUU2Q1Z3MnhBa0ZvUVZpRDJn
        Q1RpdUtGOEwzU2pEZHp6aHpXdFQ4LzQKLHKtnbchhsiuPmNcvdCXPaOZv/EJSPTC
        jsi4GJfpOlGQeB8J4/pU9LF0fEV263Lwhk/Wg09iIoZYJq74B3Vo2w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-14T05:03:45Z"
  mac: ENC[AES256_GCM,data:YthE3K6oPfR66dT4TwXOgS5f0ulM9WhxBT//dIlaIM4aVw7SwoizmiIDckcZUrSZzpFe0B7wMBD8dfM51BwIVUintQtc2A/yzk9clCZX+O6850Y/XOKqhVtkpnTK7Z6TyzMnefw2LmLzpvNbaXho6hsPsrgY9uv44qPS0IB6q+0=,iv:alNZYo/vf+LiXyZeB3t29XJW8f2ltkTw0Jirh/XbhiQ=,tag:QLWQtq50hemW6GxxMAoEpA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
