apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:E+DjuwkLHT0j5R9KPBINMQI9,iv:6C8ALQ2EtpLmgzqsrr1J2JP7oPdHJnQZ7FxXCVE6MJw=,tag:kZsVewenZzD4gpEavHMeYA==,type:str]
sops:
  age:
    - recipient: age1jth9rdg3ar3c94qjx38tw8p32xlj8pst3s709e4fedjx5dws3yqs2y8e90
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTlMyeG1XL25tVVNxcFpy
        dHlMR2VtNytjTTVMV042aCtxeDlYOFJQWGpjCno5WnNidjJGM0lIOEtMYTY2R0dQ
        dkpNbGZYczdjTE01OHk1QmJuMjh4SFkKLS0tIGMxZmYyOTVTWTlwSy9iYW9ORXZT
        RGNGNVZtOTE1eTA0US9tOXltRkZxU0EKgclHiYoT3XrO2IY1s7xGpPEpqpC05sz6
        aHQbXSknTWu6vOY6ar0K2C00oOjVVPOv5SX+A7j8VESwnN/alq4W5Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-14T05:35:19Z"
  mac: ENC[AES256_GCM,data:Z1dQYSw+STmmD7QVuTsvUMuwu/n91yjAdESiI76nOfP5kvBTwxK3Y5mWmlz5+53vSCfGEFWdZvJbEnQbWjSruI41V1FdZvSXkyJJcXhsdn7xQd+F10mA/HTBpkUA6BOHITEViBtTDodmIimhS8el4fGcf9imbqzkmx56wXlMhaQ=,iv:y3Dr6NFeLk4q0S0ZlasYUePtC0NdpiAq6NQbXyr3TDo=,tag:4yMXx0b6gTlqHb1WQ6UW7g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
