apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:LQtvG67FxrzYPXiKMAcRcTan,iv:JLZuZ/uWAT42fwyAtuMYDyXiufRjjIFyzIRvQTtPteU=,tag:2jDzQ9yDA+VEs3PaJc9ZDQ==,type:str]
sops:
  age:
    - recipient: age1jth9rdg3ar3c94qjx38tw8p32xlj8pst3s709e4fedjx5dws3yqs2y8e90
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvV1NWYXBvRmpCZk5pejk2
        akNnZFppbUZzRm1OakdVMmtCUmg1RmVDOHgwCnRNL25menhpWDI1NCtIR0MxSEFu
        NnF4OW95emMyTG9PUHUyUHVLYktIcUUKLS0tIG5XV0dkZkhybnFrU3JKTjNiMUFQ
        T3dSMEhNOWVHVi9ISi9pNjJmUzhkQjgK4V60n0RC8JGJT6bMZcHyFhAcvseDHpp1
        NYebyjuYBFddEg+H7XxilabsxDmGv8TMKKDpDNY2bEFwtVQPM0Lknw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-14T13:54:14Z"
  mac: ENC[AES256_GCM,data:LGLuuWbj8UBP3JXsn7ZYaP2hs1MNAMQiQ9+/PS9H0TYDZb2ShqqG2VIsqgG+WOaBjM+GL7gVc8pHHQeZGvfiaWtnaNadVg5wOXadmJZ5IcHdzRqZ0DZWAGa+0atenuhD5D1UNN6C+DmbAD+TA5uObhe1SA54AH3Th1gKVJJgvz0=,iv:PNbH4MzHKT41nXt2ADijIM3Fdl8MxCZ7YhPrE2v7cJo=,tag:ASN/K7gk0hnwA1Vm5ZWTYg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
