apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:i05a85Tc6Xe7pz+OrtY=,iv:baf7fr/+XFLYYR8LkhzUkulawvwhtwU/sExy3QGdYG8=,tag:m1JvRHBbVwhTchpLkloVRg==,type:str]
sops:
  age:
    - recipient: age1jth9rdg3ar3c94qjx38tw8p32xlj8pst3s709e4fedjx5dws3yqs2y8e90
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WlNPQkF3b1lvdnpZMkZ4
        a3dYRllXS2RQVFVIT0sva0JCR3BuTzhrblhZCksxbHhZRDd5ODhWQUUvMDd6dGNB
        T25aYU1sV0xWWHU2UEEzTldGZjc2NkEKLS0tIDdQTkU2KzhDdVIrRDlRd3RzWEVB
        RXVWZEdsbkhsWTR1ZVlnOC9CYXFKY0kKiiVn8kK2fV1shpDP1f928XOtIssbaeue
        xJ8ktcT2U4ZFBdylliEAVtOXsfd9T8TENOQDfRxyoJcCrY0+h5QRzQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-14T16:56:25Z"
  mac: ENC[AES256_GCM,data:QWF+F8Ob/1xNmtmdg9bWxIMTn0RrE3nHhCrIzl2kcF/i8s/BMT5ArVj8FP0jVnl/3jFydL+xLKpVj19xbgFvWqeVphsaYHotmf+XGbBuQYTjyThzhkyHT6Vn99hsOAyykyzNnD8FZBWYuxwdQWeXqw4SqKuk0OkNNnsdO8MxyW4=,iv:bynb4y7hNCM5KrxLpZOoF+q0CfHP/AIgcmrwDK/gSps=,tag:kjUEVBWrJcqvim60Tw0t/A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
