apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:opzANSMy8b8jLi82iBmRtfezvy2uVutJ88RcVIbYK0Y=,iv:q5OaP5ujOj92xOfGoD8EZU4hgdp+9l2r4Q2zEWHiaPI=,tag:FZHtTRAr/blWzFTLWrb0xg==,type:str]
sops:
  age:
    - recipient: age1jth9rdg3ar3c94qjx38tw8p32xlj8pst3s709e4fedjx5dws3yqs2y8e90
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1L0J1RCtyS1Zjbi91aHNH
        a3NCc2M0M0I5Y2FnMkVTNzVMeU43d1JLNG5NCnN4azRISnpwUDdXRFlJWlNTR3lj
        SW9rclZPbmh2OGRHTmdNS1A0Rnh6S1UKLS0tIGpvUldiWjVkcWdvbE4wa2FyTjA4
        cnpHQ2FKaHU5RkZkOU9YQjVwVDU2UlUKRAIjVz33aBpeuPZ6qCGeFi8jSUMt2YPr
        /SO27+mM76VmFj7gAhZwIJ9G4YkLzG07x7DUNDoBPEGzRtHH7eQ+OQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-14T16:56:25Z"
  mac: ENC[AES256_GCM,data:UVv0rtWLNnf4yY1sokz/Yac///a4jfOHFxpoEwUG0S+CI7T+Nct45Lp/uXIQdU9fIx+qyYRr+YoknvDNfjmRkgyuJl/uQADSnSMc5ZSPnT9cNHv11aLZkJmRXaQ999rC8gPZnvRGQLOBK//iWUucy5g5kRwoVWoAH1hj9FVmE7w=,iv:8RSvoYnwPJ8sDC9udpMPowtTvaKc3kex9Uih59Mom9M=,tag:NeZUtLYo7oxXE4ZuJx5uyQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
