apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:NAhrC/kthdT7hknu0iDNN392W/ZeXRghXZq2i5Azy7s=,iv:PF3a7MYH+N/UsTWOyC7IAaYtqdlvlfOYq3gGCM579N8=,tag:66w7FJ6v3bjloRoQn9wIMw==,type:str]
sops:
  age:
    - recipient: age1jth9rdg3ar3c94qjx38tw8p32xlj8pst3s709e4fedjx5dws3yqs2y8e90
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNT1ZaaUpkNFJHV1dXUFJT
        eWtJNEp6RW9YNlgrZFR4Zk1lREFFNVRMTW0wCkxGQmdQRTJhQ1ExUHNMbjhIYjQz
        ZXl3WS9JYUVUMHNvR2RmTmNSNlBwVVEKLS0tIFdtOEs1Nk1iQVkyaDlkTDY0dFBi
        SnUvZWlBREl4dXJjRjJzWlNrNm0zS2cKGR8A+JX7Srql+C8GRey+/ijHrHnA4fG4
        dBjIpVA/BhXW84gtf7H6Pm3ZbqSwYCUJ2W7xjGy4fWSOm6b3Qv4dsQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-14T05:03:45Z"
  mac: ENC[AES256_GCM,data:ICQQLMPEj7vT7r30ytyCAHBlp1/W8b2uKSmeIljPzgJ6M+k5I6UZKGyMmDFbXjPyBq0BM2ZKmbAl4jzP2SoBEcUhFDXkzccwoNkJhiriciBOWabPJF701gcWJ2/sBueIPsekV6ipOHYwHOtl/hna6jocrk6hmnlEekHNE8pq4qg=,iv:DsOpwT1eypKb2IVZX83t9F5H9WDJLrLwJc1YjIHX3P8=,tag:YdZHL7nc5k/UcY/pj3MPxw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
