apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:LNMvHb9TSEuK54M3jt4xc2DP7PcvKwPzXmTosong514=,iv:j+EmpBng2eUwiHZgZWAjwe8gyv3Jkr6b2mU57bCdI2w=,tag:EI2tmQvQsOwMQnjjXLP4eg==,type:str]
sops:
  age:
    - recipient: age1jth9rdg3ar3c94qjx38tw8p32xlj8pst3s709e4fedjx5dws3yqs2y8e90
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQmhrOWRpc0RQWFZyVi8v
        WkRrdHRVSGFhVXgzV0p1RjdIMytVMGEwZ0JJCm9DVVhSQmgzbUJ4aGpLUkI0Y2RN
        MXJxcUxhZ3o5OFZhaU54MHhLeW9sTjAKLS0tIGdNYkw3aFVXZTZNZy9SSzJNNVpN
        cVl0M0V1Z0dJUFZFUko0YVdDcFdRbjQKnTgdWpSrP2W5rwqO8Sg6Vk4PDR5teigy
        MSOQTlTle+oO0iIb5N/aZOajhsTPoMm2gFduQYgfguvJs20x3luoDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-14T13:54:14Z"
  mac: ENC[AES256_GCM,data:TtFEaXQv7lcCe6VqsoA50RqQMzQT+9KePe6AsmLdziaK7wRh+Dzd2+u6SQmMCUeWCTGeh0HjOYt9r7hF/vQjrV6HH6BimRoNYjfaV0LcAHx70+RAfH+sMMqPFg8AJSrLdJOcGlxW6s7XQMvoBFfeJNsO35ysRPMgLKR/ndetePQ=,iv:ZmXV+AIHUX2ST41aAhmaHOb7drTK/mZHnaGb9VKYE+0=,tag:zzWotT6zxpiC7DvGnYbRXA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
