apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Gi9vBAcqNewRdpgVpNuMd8ARnwblAup+p74F2XtQYS8=,iv:ppV0jqzdiGjwWhheDbD4RNVRbzguJ4+VrSfuMtoHZTI=,tag:lAYJlsify/msuufKVzAjcg==,type:str]
sops:
  age:
    - recipient: age1jth9rdg3ar3c94qjx38tw8p32xlj8pst3s709e4fedjx5dws3yqs2y8e90
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RjNwdGNQM1IvdUsyRDRq
        L2JKU3ZPR1pjeUZ6dWFkM2VsbFQvYmpBd21vCmtmZ2wxbllwMnV6OHFwRXVETWpi
        WnRubzFURHpCNDJjT2hDK1NmNEdpVmMKLS0tIFhabEJLUnJPcHBrQllwVWRIS2pi
        OW5HNjZCL1liQkxyUkpWS1BEUHlSUmcKA0C7VWoGq0SSc284ONvW5GwprGG1HP6F
        2aG75d2oNptR6pXr5ITY1+9QC4To2PL7aQXtIb9mCtxqkdzMa7R10g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-14T05:35:19Z"
  mac: ENC[AES256_GCM,data:V0bCRxmvB0vI+2mulNPiVWZVePYeHGbLb0mVBmTsD0W6Rsr1sHkgosvSZSBTkJDvZKyA+U1r+O4j1FBAOp0rQ3U2GvpMTZjRNUB7eH+yyAHh6YTmpsjipy+ECxPpumBH2XYYFYCdNtnlH+HwP8c8Et/WrhLhpVqiSlDdGg2xXFw=,iv:Ur+Ptl7BP5KrJ6lWzqDWXEjwXf1dqdmYQ1gACUp6aD0=,tag:jlXrF0XI/M4aZFEQWIp//A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
