apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:rwmb5c1NGXjnTnh+m5PWz8sf9aUgV+oMdUijImslhariDGDckEaM6ODMyoPBrIhCZCSv8H8HtHUbAnkxqYv0aW+P3c5EPyx1LtZv0fW4EDXwUZy71R8C75w7whiZpeSkZd7FGMz/50lgN1huIRH1ota/CGA8lF1oGZiSclWBweuUBHMCY9G6xwvB45wCEumcfQcXxaal6vCuff9AbBUsX22vJuvk72fafir1AEwhKUEmrFzC,iv:nq86ckgjKL/zTmFlq3vq3NHUQ9WY4lkcFtYmXpa14cs=,tag:DTwNkyHdQBWEcoB97IwZzQ==,type:str]
sops:
  age:
    - recipient: age1jth9rdg3ar3c94qjx38tw8p32xlj8pst3s709e4fedjx5dws3yqs2y8e90
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNFBTekRoNDdFU0Fsb1ky
        aTlkVFhoNytnMnpQaHFFcG02d0xiczB5b0FNCmhmRUpycXJsbHJUNG5ZSlhPbVJM
        UzJkRzNFWHE5SWhkTC9CVkdPRUxaUFUKLS0tIE5JbUIwaXJpcUd4N1pQSGNBdDRP
        V3V6aytXV2pYdlgySGZRcVJJb0lmRnMKCigHOcm14aZg7M6HxYVs4NqTWhG6AaM4
        6gLUea6VivPuno4AuLmuTYQ0P+0caCTI1jwoOG9Tn+fKqrtFaMYGZQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-14T16:56:25Z"
  mac: ENC[AES256_GCM,data:p84lZsWsmOfIuHmklhwXLu3tpYsOpzI+TWBJgj5sk57dvRuRHCmB9l58k9ij7BThbGvPr7yyKwAkHZQkB0OF7h579Pb4Tw+EV2oGbkVAuk43/VxkyVU6wAheTnA5Ox8ztsikMpeyP4l3hKFXhmf0Yhh1C57ztXDWLIVsHwGqILQ=,iv:TBtUpeyJDBaqU+Pr1edHun1OOrwDPwq3O/EClkUMvsc=,tag:XUjQJnScZxLBGMoQrs6CLQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
