apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:v7Eh4vi9yc1wAfDDmkbMBKS3fyafXh/0SF3Gk3eSR+ysk7G7ORy5RO/zyaJAGX9QUDCex6uFa6YlcP3ETyeF+rmiAvjQAYJ+YujLEUJWVQuZALxVCFYzaHX/+Q8fxkifyjh29oR9+tnFAQK/x90q5EpSexPC6gHN3MIbm3CLsu9SLP+ZmX4U8mL9EQM9nNL+TNOIxBtvKpl5AvM10C3aG5IvxPJPbdApHK6Tdf+zAQQ4Z+Du,iv:eOy1zUUqoHUU1N1C5wbeZ/9NYhxLXMXP/ZTPr3sQJnE=,tag:O+IxXdT0vDY4U9rU0EyeBQ==,type:str]
sops:
  age:
    - recipient: age1jth9rdg3ar3c94qjx38tw8p32xlj8pst3s709e4fedjx5dws3yqs2y8e90
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MWdoT3J5ZnlFaEZQT2hq
        amVVQnNuMk9IRUZWalhTN1oyYWVvUWh2R2lRCjl6bThjNDN1RE1wMHphUXJjc3FL
        SDZXeVdMNloyTU94eHJFazE2clNwR3cKLS0tIGljNExIMWI0bGlEdHlnRTFoKy9W
        c2ExSXdBRlJMYS94UlhiL1JZbEFGdEkKpNGb91M2m1Te/k8BdkH/uL0uXDvQVgpl
        qEeiaexC5e/nOrauBc10JRqUAOTUZYhtitFbvhuONQ1cUTca9PV+IQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-14T05:35:19Z"
  mac: ENC[AES256_GCM,data:sUGkA3VJm7STO+tRJCeXqrDZVVOe+RuAUn6teC9o8D3rldy1+oyT4O/MuvPxGWK8LIOVgRo3auFGLLaOVk81YVDjCraVA/uMbjTPu4GZGGl/Apbr/403KJLZjnwGTYb9kwJ2O2W+44pf3WGu5yhVCnClzkYKyqB3yzMTyaqnJSA=,iv:QAuEsAuyBvxRENCllQDytnxzJ203Is3/PWjlSJw73fU=,tag:VVfr9Y8bOUJd3TdStqxDmg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
