apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:XAsbvpMLRfRYUaq4GwUdC+A07BUPQwgOxfGVV7V9Klqdac70/srSElH+cEqq1yL6zxUGTVCu3IXfDy0iLmrLpIIY+GH9i2JlqP+oVQLybrmiJtYSD3PktmIK4yxFtT0wHYXG8Pl9acitOth9K0ojPOALcqEIRwznQZw/GKqoBEo9OG9uOUyGF4ypQOOm9q+cRs51XprOGxs+pW39wwTSaCyCoW7I2AcWSEfJpO/MdWZHZ/hN,iv:pR2HZ0dIGoFmN67mtWk4vrGuLMHxARJtHIw0EH3sZyk=,tag:kC6rfqviDYF7BznGHdIUwA==,type:str]
sops:
  age:
    - recipient: age1jth9rdg3ar3c94qjx38tw8p32xlj8pst3s709e4fedjx5dws3yqs2y8e90
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOXovSHJldGJ3Z0JUeFo2
        bU05Y21DbldyZE8vWmdxd2dhT0JHWmdmcFRVCjdhUXZlZVFrbDFBbmhQK20wa25q
        WFFUVVVIalZBZDlwVjVFaGZXTGRPeEEKLS0tIDM2Q1VneVE1U3hLc0hqUzNhcGhP
        MUd4OTNGRExlM1V6S3FmUTY0S0dBaFkKSqbb+ehbYg4mQWtjI/u+/AFVYv03kr92
        7U5Ogu2Yz9WyB0KwgY3WusQZyBQx5gnUzp2OV+p2Hux9i4BbQpyEPg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-14T13:54:14Z"
  mac: ENC[AES256_GCM,data:bNNfNoZup8E5nO3ZNov2YV1q9+oAc58kCmBsRHhR6HUaCKWazfoGeSxwz7QEVtn5kIdU6ZrxxRfDAiCJqqGqqWNJmaG0aXDnK6potgks4XP6w1PR2vUBFAew1+OWlTFsT8KsTmHddhoXXYlStQf1jBTaEQSvgGED9UgmYjgRI3c=,iv:MbfI1ByxsGoclRD+GbK7c5IiZpYDt7nLG0TcwuPUulM=,tag:/C07eXLV33wHE7f6OgoGIw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
