apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:rdJ8zM1HmCnDU9lhEcaJW4zN1daQtOIp4NHBbRbA38LTIZAB2kpkTLPG/1AyWqpYH5U/VinOaqiLjo6+Gp2oLtn0RMgjt8xeLp80KeWcm+a7jmhmhkUEUAXnDc6oZFzytdgnKOkXi5aGHmTvNJoo64xo/gUXmrQfDjrfAPPiY4TuzuvCfrLvPwR0uZCU2JyvvpKO/5QGvGZzvmnfPnSf0P/MbAN1eJQdPFWjASwdLq3URjSb,iv:QehxFwqT1XHBvVkg03Da9zl8hnY8u6asfvFViIJBhYI=,tag:9zA4z6dJyn7ro8wFVZ/Rqw==,type:str]
sops:
  age:
    - recipient: age1jth9rdg3ar3c94qjx38tw8p32xlj8pst3s709e4fedjx5dws3yqs2y8e90
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCazAzYjdLV1NxeUNwK3Nw
        YUYzczBVQnBEV1NVZ0RKYndnQVYzZDAySXpRCk5KcjhYN3JnMnNxZGVMNnRwQnlO
        bkxCaTdMbVNRRlVNMVgvWWFFcFl3blUKLS0tIHhDWXdnQ2F1aVZoZ3cwQU5IeXVG
        cE9iVUpqK2tvaDhEa1g5SUkrTlVsRU0KSiTcQ7eqTeDLP3Af49qG6jskBVmO4kEX
        2ZP6K7/9oqx3q6vDK7a70wW1AF+kE8ZFDqvTqIxjzvq5Own64F+eHQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-14T05:03:46Z"
  mac: ENC[AES256_GCM,data:4+Qu9DY4shOnHvjGSPFqe68Wz7KexydgFLWHcrasnq0MclPYriG8akXH5McAC1kVJqn+h7sL39fos4UDnKCYGg1HG02LPVd9r0r8Q5eY5fmxHUKX08Vp0Vb1seOE10AgMwOEw8OM13UAGvwY1jOQ/65MjTShGdcP1+OXMRUuzi0=,iv:wbLtjQI5TvJ9LCa0hS7sCdlD0aa86x90AACY+GQaYwQ=,tag:HtqixuQZ2jVMzk/jB9yyZw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
