apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:salc0EqCtuj9Y9SfntIjRLMAZYY6lRjSxVLILFhWY9XqFd4nzmgHSQ==,iv:Rms+FeB+7UzsD2MSU1lBjpwjzi1qqt/mF676ERfXMzg=,tag:Vph8pYJDydGzWLC/mREbVg==,type:str]
sops:
  age:
    - recipient: age1jth9rdg3ar3c94qjx38tw8p32xlj8pst3s709e4fedjx5dws3yqs2y8e90
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYXdjTWRIRTE4SURzZVNo
        VVdHckFlMWVPZ3luQzlad3pDS2xqZ3BSVXkwCjltN1BpeFo3dENKV2RQKzhYQTNl
        cG5DMTNRYW1YTk1oem80LytKLzRnalEKLS0tIDE0UlloeEtWYVBNV2djVW5hZkFy
        UnhtKzRXWGFSQ1c0Y29ySXB5YXVFSzgKtSQxmtVYTP/JqEAYsd5gMWI+MKBcfXcG
        3t7VmWhby9OiCRs1Nj/MsavqvM13HLlwgbRcGxSEzDuXRbS/UFC0eQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-14T05:03:45Z"
  mac: ENC[AES256_GCM,data:m3Fmy8AashWj2OQrIrPrhPHuKqKSCdCoco76Am61d58j30exc9z4Y3E2x2YmCnralMQm6ZKrB6S+3sP34+28bqti3z1HdlB5uwY5LyL2QaXMLx6PXr1ficGIp4btcxoAkSJpGRzrj/SHPQykJRMBobtX6IVqCVcsEYrMPD7lXGI=,iv:6d//exOuQLYP+J/5+5FPHj6QkUV9YR6laArxyPoq1vc=,tag:/SNX1UOY+1b27SWH7XNCbQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
