apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:R9o40GSXBfMLGpaKdHQPRmkToifYeWNV5Lj0jKgzE6dFH7mSQB93bw==,iv:lXC4BNN6B8C8haXXisZvROQl9+7xgB2gVxYtx1jSO8Q=,tag:5KJWBxkSX7HEGdbPMCLQPw==,type:str]
sops:
  age:
    - recipient: age1jth9rdg3ar3c94qjx38tw8p32xlj8pst3s709e4fedjx5dws3yqs2y8e90
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbnlBdWF0YkVwUHl0cDFh
        UUo1bU9tSDlRSGF5RWFyN1o3TENwMm1ISTJjCml3Rm9lYVBtbm1ZZkt6Wm9SS0hJ
        TVEvRXJNOTA0VFp2eXNlZkZscnAyZmMKLS0tIHl3V3YwSk0xUUtZUHR2Q1dMU1px
        NWMzR0VBQVlyOHpnSUkwQ3ZDQytQS0EKxuCYvlvwF755x5oRkgw7+t7RN4Y7RF0H
        dWcrK77jUommwowNhE36Fd8hS8T3Rx4dCuIQgCuM4JY22IGoPlk5Fw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-14T13:54:14Z"
  mac: ENC[AES256_GCM,data:Y3ucp9Zbe5HmWuufxrCTNBxSyCQ7dvyE6AGcx68kScL5xAfii4ZMeboPbz/0Z9gp/nQCKzRtuwcYDBR5WxsmVniXMs8JpWoaSUuhjpPxd5sfiwGiMr1hwZtFUkD3nAXCTCv4zCPZ3HT6Wg7KhNRCfIhr9/VjYe5ZQxf/B8wDY4Y=,iv:TpqzaIddshfkW3yG9gt932yZZQi+HZ1+MWe05tBYssw=,tag:IM7AKG4vamir5rHLioYdrA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
