apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:0tiZbsJLZ+jspVfnRTddVfGUeD6dHsvz565gUs5+fRd56N063dop7g==,iv:1qlQRlu3/Qz5CNHwfyoOgI22gSEHWlnH5hIDHYH5Zqg=,tag:pYakA1hyQO37kc0krJOpsw==,type:str]
sops:
  age:
    - recipient: age1jth9rdg3ar3c94qjx38tw8p32xlj8pst3s709e4fedjx5dws3yqs2y8e90
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQWx0SG1TY2diclJFRm9D
        Nmp1Yndpa2ZwUDdKTUhvaVY4NUFhRjZVV2pvCmNPdGhtNzJlcDEzQWFSMXJlaVo1
        ZkdaT3Erb0s1T0VFZTN4MS83QmlxRUEKLS0tIEYzanJnRXE3RlVhWDJUZ3NjM0xR
        VjNON0xPOGNnbHFTd2NzMTNvWG54ME0KNuYp4tN0G1KOGMY+w4yghUDyf/xx6MkX
        rOUszDX1KPfbhGBcTpcbKZ5ReM3udHeDs3XRbbt0H9zz05X5jDUPHg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-14T16:56:25Z"
  mac: ENC[AES256_GCM,data:tOw9hE7TKXzhwxoKMByHwOJTUzBEwmH1ygOGWP1c/Zemszw4fapsJdLsqnhsqof+XxF15fDKmGbxYjLnkB6gZbB/GXXpfddvA0lZqPMaD5gxaSYyEPgca4MaTNhGuYFbjFS5kSmjJrcK9ax4ry7hBOLtuDiacxOPxYSHy0wLHqw=,iv:vnIJNaqsoo7/yjcC3j8I5Xa7Ef5a4Q9ap+kMNQzc0Vg=,tag:Dgzv6aLEPYC1/Vg76S3Lvg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
