---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.99.0.203:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.99.0.203"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "talos01"
    ipAddress: "10.99.0.200"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:50:56:b4:cd:91"
        dhcp: false
        addresses:
          - "10.99.0.200/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.99.0.1"
        mtu: 1500
        vip:
          ip: "10.99.0.203"
  - hostname: "talos02"
    ipAddress: "10.99.0.201"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:50:56:b4:20:e5"
        dhcp: false
        addresses:
          - "10.99.0.201/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.99.0.1"
        mtu: 1500
        vip:
          ip: "10.99.0.203"
  - hostname: "talos03"
    ipAddress: "10.99.0.202"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:50:56:b4:f9:fc"
        dhcp: false
        addresses:
          - "10.99.0.202/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.99.0.1"
        mtu: 1500
        vip:
          ip: "10.99.0.203"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

